export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_REMOVAL = "FILE_REMOVAL";

export const CHANGE_MAP_STYLE = "CHANGE_MAP_STYLE";
export const UPDATE_LAYER_SETTINGS = "UPDATE_LAYER_SETTINGS";
export const MAP_HOVER = "MAP_HOVER";

export const CHART_HIGHLIGHT = "CHART_HIGHLIGHT";
export const CHART_SELECT = "CHART_SELECT";
export const CHANGE_ACTIVE_CHART = "CHANGE_ACTIVE_CHART";
export const MODE_HIGHLIGHT = "MODE_HIGHLIGHT";
